language: erlang
before_install:
  - sudo apt-get install xsltproc
before_script:
  - "make get-lfetool"
  - "make copy-appsrc"
script:
  - "make check-travis"
notifications:
  irc: "irc.freenode.org#billo"
  recipients:
    - eng@billo.systems
otp_release:
  - 17.3
  - 17.1
  - R16B03
  - R15B03
